#!/usr/bin/env -S tsx
import fs from 'fs';
import path from 'path';

const root = path.join(process.cwd(), 'packages', 'scanners', 'sites');
fs.mkdirSync(root, { recursive: true });

const peopleSites = [
  '24counter.com',
  '411.com',
  '411.info',
  '411locate.com',
  'absolutepeoplesearch.com',
  'address.us.com',
  'addresses.com',
  'advancedbackgroundchecks.com',
  'alabamacourtrecords.us',
  'alaskacourtrecords.us',
  'allareacodes.com',
  'allpeople.com',
  'americaphonebook.com',
  'anywho.com',
  'arivify.com',
  'arizonacourtrecords.us',
  'arkansascourtrecords.us',
  'arrestfacts.com',
  'backgroundcheck.run',
  'backgroundcheckers.net',
  'beenverified.com',
  'besthistorysites.net',
  'bumper.com',
  'californiacourtrecords.us',
  'callercenter.com',
  'cellrevealer.com',
  'centeda.com',
  'checkpeople.com',
  'checksecrets.com',
  'clubset.com',
  'clustrmaps.com',
  'coloradocourtrecords.us',
  'confidentialphonelookup.com',
  'connecticutcourtrecords.us',
  'corporationwiki.com',
  'councilon.com',
  'courtcasefinder.com',
  'criminalregistry.org',
  'cyberbackgroundchecks.com',
  'dataveria.com',
  'delawarecourtrecords.us',
  'familytreenow.com',
  'fastbackgroundcheck.com',
  'fastpeoplesearch.com',
  'fastpeoplesearch.info',
  'fastpeoplesearch.io',
  'fastpeoplesearch.org',
  'fastpeoplesearch.us',
  'fastpeoplesearch.biz',
  'fastpeoplesearch.xyz',
  'fastpeoplesearch-other',
  'fastpeoplesearch-other2',
  'fastpeoplesearch-other3',
  'fastpeoplesearch-other4',
  'fastpeoplesearch-other5',
  'fastpeoplesearch-other6',
  'fastpeoplesearch-other7',
  'fastpeoplesearch-other8',
  'fastpeoplesearch-other9',
  'fastpeoplesearch-other10',
  'fastpeoplesearch-other11',
  'fastpeoplesearch-other12',
  'fastpeoplesearch-other13',
  'fastpeoplesearch-other14',
  'fastpeoplesearch-other15',
  'fastpeoplesearch-other16',
  'fastpeoplesearch-other17',
  'fastpeoplesearch-other18',
  'fastpeoplesearch-other19',
  'fastpeoplesearch-other20',
  'fastpeoplesearch-other21',
  'fastpeoplesearch-other22',
  'fastpeoplesearch-other23',
  'fastpeoplesearch-other24',
  'fastpeoplesearch-other25',
  'fastpeoplesearch-other26',
  'fastpeoplesearch-other27',
  'fastpeoplesearch-other28',
  'fastpeoplesearch-other29',
  'fastpeoplesearch-other30',
  'findpeoplesearch.com',
  'findrec.com',
  'floridacourtrecords.us',
  'floridaresidentsdirectory.com',
  'freepeopledirectory.com',
  'freepeoplesearch.com',
  'georgiacourtrecords.us',
  'golookup.com',
  'hawaiicourtrecords.us',
  'hodges-directory.us',
  'homemetry.com',
  'idahocourtrecords.us',
  'idstrong.com',
  'idtrue.com',
  'illinoiscourtrecords.us',
  'indianacourtrecords.us',
  'information.com',
  'inforver.com',
  'infotracer.com',
  'inmatessearcher.com',
  'instantcheckmate.com',
  'intelius.com',
  'iowacourtrecords.us',
  'kansascourtrecords.us',
  'kentuckycourtrecords.us',
  'kidslivesafe.com',
  'kwold.com',
  'lookify.io',
  'mashpanel.com',
  'mugshotlook.com',
  'mylife.com',
  'nationalpublicdata.com',
  'neighbor.report',
  'neighborwho.com',
  'newenglandfacts.com',
  'northcarolinaresidentdatabase.com',
  'numberguru.com',
  'numberville.com',
  'nuwber.com',
  'officialusa.com',
  'ofsearch.org',
  'ohioresidentdatabase.com',
  'oldphonebook.com',
  'onlinesearches.com',
  'ownerly.com',
  'peekyou.com',
  'people-background-check.com',
  'people.yellowpages.com',
  'peoplebyname.com',
  'peoplebyphone.com',
  'peoplefinders.com',
  'peoplelooker.com',
  'peoplesearch.com',
  'peoplesearch123.com',
  'peoplesearcher.com',
  'peoplesearchexpert.com',
  'peoplesearchnow.com',
  'peoplesearchusa.org',
  'peoplesmart.com',
  'peoplewhiz.com',
  'peoplewin.com',
  'personsearchers.com',
  'persontrust.com',
  'phonebooks.com',
  'plcom.net',
  'privatenumberchecker.com',
  'privaterecords.net',
  'privatereports.com',
  'propeoplesearch.com',
  'property.whitepages.com',
  'pub360.com',
  'publicdatacheck.com',
  'publicdatadigger.com',
  'publicdatausa.com',
  'publicinfoservices.com',
  'publicrecordreports.com',
  'publicsearcher.com',
  'quickpeopletrace.com',
  'radaris.com',
  'recordsfinder.com',
  'rehold.com',
  'revealname.com',
  'revealphoneowner.com',
  'reversephonecheck.com',
  'reversephonelookup.com',
  'sealedrecords.net',
  'searchpeoplefree.com',
  'searchpublicrecords.com',
  'searchquarry.com',
  'searchsystems.net',
  'secretinfo.org',
  'simplecontacts.com',
  'smartbackgroundchecks.com',
  'socialcatfish.com',
  'spokeo.com',
  'spyfly.com',
  'stage-research.net',
  'staterecords.org',
  'telephonedirectories.us',
  'tennhelp.com',
  'texasarrestwarrants.org',
  'texaswarrantroundup.org',
  'thatsthem.com',
  'thisnumber.com',
  'topwa.org',
  'truepeoplesearch.com',
  'truthfinder.com',
  'truthrecord.org',
  'unitedstatesphonebook.com',
  'usa-people-search.com',
  'usatrace.com',
  'usphonebook.com',
  'usphonepro.com',
  'ussearch.com',
  'verecor.com',
  'vericora.com',
  'veriforia.com',
  'veripages.com',
  'virtory.com',
  'weinform.org',
  'wellnut.com',
  'whitepages.com',
  'yankeegroup.com',
  'yellowbook.com',
  'yellowpagesdirectory.com',
  'zabasearch.com',
];

const mirrorSites = [
  'addresssearch.com',
  'affordablebackgroundchecks.com',
  'backgroundchecks.org',
  'backgroundrecords.com',
  'callercomplaints.com',
  'criminal.com',
  'criminalrecords.com',
  'ctarrests.org',
  'dewarrants.org',
  'divorcerecordsbyname.org',
  'dobsearch.com',
  'easybackgroundchecks.com',
  'federalinfotrace.com',
  'flarrests.org',
  'freebackgroundcheck.io',
  'freebackgroundcheck.org',
  'freebackgroundchecks.com',
  'freebackgroundchecksusa.com',
  'freepeoplescan.com',
  'freepeoplesearch.io',
  'freephonetracer.com',
  'govarrestrecords.org',
  'govbackgroundchecks.com',
  'governmentregistry.org',
  'govwarrantsearch.org',
  'kingsburycountyjail.org',
  'msarrests.org',
  'nyarrests.org',
  'onlinepeoplesearch.com',
  'oregonarrest.org',
  'oregonpublicrecords.org',
  'peoplefinder.com',
  'persopo.com',
  'phonenumberlookup.online',
  'profile.systems',
  'publicrecordcenter.com',
  'publicrecords.com',
  'publicrecords.searchsystems.net',
  'publicrecords.site',
  'publicrecordscenter.org',
  'publicrecordsofficial.com',
  'publicrecordsreviews.com',
  'publicsrecords.com',
  'recordsfindhj.com',
  'scarrests.org',
  'sdarrests.org',
  'sheriffsdepartment.net',
  'snoopstation.com',
  'texasarrests.org',
  'top4backgroundchecks.com',
  'truepeoplesearch.io',
  'truthviewer.com',
  'unitedstatesbackgroundchecks.com',
  'usfriendsreunited.com',
  'usrecords.net',
  'uswarrants.org',
  'verifyarrestwarrant.com',
  'vtarrests.org',
  'wvarrests.org',
];

const all = [...peopleSites, ...mirrorSites];

function stubCode(domain: string, mirrorOf?: string) {
  const opt = domain.includes('fastpeoplesearch-other') ? 'https://www.fastpeoplesearch.com/remove' : '';
  const robots = 'unknown';
  return `import type { SiteAdapter } from '@/lib/types';
const adapter: SiteAdapter = {
  id: '${domain}',
  supportsInputTypes: ['name','email','phone','address','username'],
  metadata: { robotsStatus: '${robots}', optOutUrl: '${opt}', lastChecked: new Date().toISOString()${mirrorOf ? ", mirrorOf: 'fastpeoplesearch.com'" : ''} },
  async buildQueries(input) { return []; },
  async parse(html, url) { return []; },
  match(candidate, input) { return { matched: false, matchedFields: [], reason: 'Stub adapter', confidence: 0 }; }
};
export default adapter;
`;
}

const filesWritten: string[] = [];
for (const d of all) {
  const file = path.join(root, `${d}.ts`);
  if (!fs.existsSync(file)) {
    const isMirror = d.startsWith('fastpeoplesearch-other');
    fs.writeFileSync(file, stubCode(d, isMirror));
    filesWritten.push(file);
  }
}

// Generate registry file
const registryPath = path.join(process.cwd(), 'packages', 'scanners', 'registry.ts');
const imports: string[] = [];
const adaptersArr: string[] = [];
for (const d of all) {
  const varName = d.replace(/[^a-zA-Z0-9]/g, '_');
  imports.push(`import ${varName} from './sites/${d}';`);
  adaptersArr.push(varName);
}
const registryCode = `${imports.join('\n')}\n\nexport const allAdapters = [${adaptersArr.join(', ')}];\n`;
fs.writeFileSync(registryPath, registryCode);

console.log(`Generated ${filesWritten.length} adapter stubs and registry.`);
