// Core types for the SOC simulation engine

export type LogSource = 'sysmon' | 'zeek' | 'suricata' | 'edr' | 'cloudtrail' | 'windows-event';

export type AttackStage = 
  | 'initial-access'
  | 'execution'
  | 'persistence'
  | 'privilege-escalation'
  | 'defense-evasion'
  | 'credential-access'
  | 'discovery'
  | 'lateral-movement'
  | 'collection'
  | 'command-and-control'
  | 'exfiltration'
  | 'impact';

export interface SimulatedEvent {
  id: string;
  source: LogSource;
  scenario_id: string;
  session_id: string;
  technique_id: string; // MITRE ATT&CK technique ID
  stage: AttackStage;
  timestamp: string;
  details: Record<string, any>;
  
  // Correlation fields
  related_event_ids: string[];
  correlation_key?: string; // e.g., same IP, same process, same user
  
  // Context for drill-down
  process_tree?: ProcessTreeNode;
  network_context?: NetworkContext;
  threat_score?: number; // 0-100
}

export interface ProcessTreeNode {
  process_id: string;
  process_name: string;
  command_line: string;
  parent_id?: string;
  children: ProcessTreeNode[];
  timestamp: string;
  user: string;
  hostname: string;
}

export interface NetworkContext {
  source_ip: string;
  dest_ip: string;
  source_port: number;
  dest_port: number;
  protocol: string;
  bytes_sent: number;
  bytes_received: number;
  duration: number;
  related_connections: string[]; // IDs of related connections
}

export interface AttackChain {
  id: string;
  scenario_id: string;
  session_id: string;
  name: string;
  description: string;
  stages: AttackChainStage[];
  status: 'active' | 'completed' | 'detected' | 'failed';
  start_time: string;
  end_time?: string;
  detected_at?: string;
}

export interface AttackChainStage {
  stage: AttackStage;
  technique_id: string;
  technique_name: string;
  timestamp: string;
  success: boolean;
  events: string[]; // Event IDs generated by this stage
  artifacts: AttackArtifact[];
  description: string;
}

export interface AttackArtifact {
  type: 'ip' | 'domain' | 'hash' | 'file' | 'process' | 'user' | 'registry_key';
  value: string;
  context: string;
  discovered_at: string;
}

export interface ScenarioStory {
  id: string;
  name: string;
  description: string;
  initial_infection_vector: 'phishing' | 'usb' | 'drive-by' | 'supply-chain' | 'credential-theft' | 'valid-accounts';
  attack_chains: string[]; // Attack chain IDs
  timeline: ScenarioTimelineEvent[];
  learning_objectives: string[];
  difficulty: 'grasshopper' | 'beginner' | 'intermediate' | 'advanced';
  narrative?: {
    background: string;
    incident: string;
    yourRole: string;
  };
}

export interface ScenarioTimelineEvent {
  timestamp: string;
  stage: AttackStage;
  description: string;
  visible_to_user: boolean; // Whether this event is shown in the timeline
  detection_triggered: boolean;
}

export interface DetectionRule {
  id: string;
  name: string;
  query: string; // KQL/Lucene query
  mitre_techniques: string[];
  severity: 'low' | 'medium' | 'high' | 'critical';
  enabled: boolean;
  threshold?: number;
  time_window?: string;
}

export interface GeneratedAlert {
  id: string;
  rule_id: string;
  rule_name: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  timestamp: string;
  events: string[]; // Related event IDs
  technique_id: string;
  stage: AttackStage;
  context: Record<string, any>;
  threat_score: number;
}

