services:
  - type: web
    name: threatrecon-labs-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: FRONTEND_ORIGIN
        value: https://threatrecon.io
      - key: REDIS_URL
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
